config/routes.rb
Buyproofed::Application.routes.draw do
  get "static/about"
  get "static/contact"
  get "static/privacy"
  get "index/home"
  get "index/show"
  get "index/search"

  get "index/connect"

  get "index/callback"
  get '/oauth/callback' => 'index#callback'

  root to: 'index#search'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
require "twitter"
require "instagram"
require 'youtube_it'

class IndexController < ApplicationController

  def search
  end

  def home


    @search_query = params[:query]
    @search_index = 'All'

    if params[:query]
      req = Vacuum.new

      # Config request
      req.configure(
      aws_access_key_id:     'AKIAJLHZP6KG2I4UFWQA',
      aws_secret_access_key: '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',
      associate_tag:         'buyproofedcom-20'
      )

      # Set params for Amazon API
      params = {
        'SearchIndex' => @search_index,
        'Keywords'    => @search_query,
        'ResponseGroup' => 'Large',
        'ItemPage'    => 1
      }

      # Call ItemSearch method
      res = req.item_search(query: params)

      # Create hash from xml respond
      @item = res.to_h
      @response = @item['ItemSearchResponse']
      @items= @response['Items']

      #Except bad tags
      @items_iterator =  @items.except('Request').except('TotalResults').except('MoreSearchResultsUrl').except('TotalPages')
    end
    if @search
      @search = params[:query]
    end

    # Config Twitter API
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "Jwc3RAEcGTEFTkIdPYNHxvPOI"
      config.consumer_secret     = "A0IsgS5kCJjELeFD8Ri6yhHl5mNq1iOQJAVREbnEsJwZfzDarG"
      config.access_token        = "422478040-eh98DggYKekATjBjt2y12GniTwfzRjbONYeF7SkL"
      config.access_token_secret = "cV6exbs9iqCa4aG38twMbNDiAtQDDrQODlUtSwZ6L0i0d"
    end

    #config youtube Api

    @client_youtube = YouTubeIt::Client.new(:username => "buyproofed@gmail.com", :password =>  "prelude01", :dev_key => "AI39si7KluyKh5GU_AasgkPADGDNSlayqaL3l-Ef1WXtkEEL9F9OUJ7SGjBORv1mf5zD3faI-R7iLrczJ3a8aQ6fUzWlZOr9BQ")


    #config Google plus
    GooglePlus.api_key = 'AIzaSyAehb4IWY7X1n4HgXGdKcER3R45jEGB2N4'

    # Create Respond for Ajax
    respond_to do |format|
      format.html
      format.js
    end

  end

  def show
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
    @index_array = [["Categories", "All"] ,'All','ArtsAndCrafts', 'Automotive', 'Baby', 'Beauty', 'Blended', 'Books', 'Classical', 'Collectibles', 'DigitalMusic', 'Grocery', 'DVD', 'Electronics', 'HealthPersonalCare','HomeGarden', 'Industrial', 'Jewelry', 'KindleStore', 'Kitchen', 'LawnGarden', 'Magazines', 'Marketplace', 'Merchants', 'Miscellaneous', 'MobileApps', 'MP3Downloads','Music','MusicalInstruments','MusicTracks','OfficeProducts','OutdoorLiving', 'PCHardware', 'PetSupplies', 'Photo', 'Shoes', 'Software', 'SportingGoods', 'Tools', 'Toys', 'UnboxVideo', 'VHS', 'Video', 'VideoGames', 'Watches', 'Wireless', 'WirelessAccessories']


        @search_query = params[:query]
        @search_index = params[:index]
  end

  def contact
    @index_array = [["Categories", "All"] ,'All','ArtsAndCrafts', 'Automotive', 'Baby', 'Beauty', 'Blended', 'Books', 'Classical', 'Collectibles', 'DigitalMusic', 'Grocery', 'DVD', 'Electronics', 'HealthPersonalCare','HomeGarden', 'Industrial', 'Jewelry', 'KindleStore', 'Kitchen', 'LawnGarden', 'Magazines', 'Marketplace', 'Merchants', 'Miscellaneous', 'MobileApps', 'MP3Downloads','Music','MusicalInstruments','MusicTracks','OfficeProducts','OutdoorLiving', 'PCHardware', 'PetSupplies', 'Photo', 'Shoes', 'Software', 'SportingGoods', 'Tools', 'Toys', 'UnboxVideo', 'VHS', 'Video', 'VideoGames', 'Watches', 'Wireless', 'WirelessAccessories']


        @search_query = params[:query]
        @search_index = params[:index]
  end

  def privacy
    @index_array = [["Categories", "All"] ,'All','ArtsAndCrafts', 'Automotive', 'Baby', 'Beauty', 'Blended', 'Books', 'Classical', 'Collectibles', 'DigitalMusic', 'Grocery', 'DVD', 'Electronics', 'HealthPersonalCare','HomeGarden', 'Industrial', 'Jewelry', 'KindleStore', 'Kitchen', 'LawnGarden', 'Magazines', 'Marketplace', 'Merchants', 'Miscellaneous', 'MobileApps', 'MP3Downloads','Music','MusicalInstruments','MusicTracks','OfficeProducts','OutdoorLiving', 'PCHardware', 'PetSupplies', 'Photo', 'Shoes', 'Software', 'SportingGoods', 'Tools', 'Toys', 'UnboxVideo', 'VHS', 'Video', 'VideoGames', 'Watches', 'Wireless', 'WirelessAccessories']


        @search_query = params[:query]
        @search_index = params[:index]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/index/_amazon_review.html.haml
.hide
  = @asin = params[:asin]
  - if @asin
    =@asin
  - else
    =@asin = '11111111'
  = rev = Vacuum.new
  = rev.configure(aws_access_key_id: 'AKIAJY35B3LNL425ROFQ',aws_secret_access_key: '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',associate_tag:'coffee')
  = params = {'ItemId' => @asin.to_s, 'ResponseGroup' => 'Reviews','ItemPage' => 1}

  .hide= rev_res = rev.item_lookup(query: params)
  = url = rev_res.to_h
  = iframe = url['ItemLookupResponse']['Items']['Item']['CustomerReviews']['IFrameURL']

%iframe{:src => "#{iframe}", width: '100%', height: '400px' }

app/views/index/_amazon_reviews.html.haml
= review = Vacuum.new

  = review.configure(aws_access_key_id:     'AKIAJY35B3LNL425ROFQ',aws_secret_access_key: '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',associate_tag: 'coffee')

app/views/index/_google_plus.html.haml
.hide= @r = GooglePlus::Activity.search('Review ' + params[:stw], 'maxResults' => 5)
.hide=i = 0
- @r.each do |google|
  .hide= i = i + 1
  =link_to google.title, google.url, target: '_blank', class: 'google_link'
  - if i > 4
    - break

app/views/index/_instagram.html.haml
=@client_inst = Instagram.client(:access_token => session[:access_token])

=@tags = @client_inst.tag_search(params[:stw])


-if @tags.empty?
  %p Bad
-else
  = @tags[0].media_count
  -for media_item in @client_inst.tag_recent_media(@tags[0].name)
    =image_tag media_item.images.thumbnail.url

app/views/index/_twitter.html.haml
.tweets_block
  = @client.search('"Review ' + params[:stw] + '"').take(5).collect do |tweet|
    .tweet
      =image_tag tweet.user.profile_image_url, class: 'twitter_avatar'
      .twitter_content
        .twitter_user_name=tweet.user.screen_name
        .twitter_time= time_ago_in_words(tweet.created_at)
        .clearfix
        .twitter_text= tweet.text
        -tweet.urls.each do |t|
          =link_to t.to_h[:url], t.to_h[:url], class: 'twitter_link'
        %br
      .clearfix

app/views/index/_youtube.html.haml
.hide=@youtube_search = @client_youtube.videos_by(:query => 'Review ' + params[:stw], :per_page => 5)
- if @youtube_search
  .hide=@youtube = @youtube_search.videos
  -if @youtube.empty?
    %p No videos
  -else
    .hide=loop = [0,1,2,3,4]
    -loop.each do |i|
      -if @youtube[i].nil?
      -else
        %br
        %iframe{allowfullscreen: "", frameborder: "0", height: "315", src: "//www.youtube.com/embed/#{@youtube[i].video_id.to_s.gsub!('tag:youtube.com,2008:video:','')}", width: "560", class: 'youtube__video'}
        %br

app/views/index/home.html.haml
.l-SearchResults

  = render partial: 'index/partial/header'
  %br
  %br
  = render partial: 'index/partial/items'

app/views/index/home.js.erb
var item = localStorage.item_count;

$('.social_button_'+item).parent().parent().children('.tabs__sections').children('.section__social').children('.soc_tabs').children('.soc_tabs_section').children('.soc_tabs_twitter').html("<%=j render :partial => 'twitter' %>");
$('.social_button_'+item).parent().parent().children('.tabs__sections').children('.section__youtube').html("<%=j render :partial => 'youtube' %>");

$('.social_button_'+item).parent().parent().children('.tabs__sections').children('.section__social').children('.soc_tabs').children('.soc_tabs_section').children('.soc_tabs_google').html("<%=j render :partial => 'google_plus' %>");

$('.social_button_'+item).parent().parent().children('.tabs__sections').children('.section__reviews').html("<%=j render :partial => 'amazon_review' %>");


var loaded = true;

if (loaded === true) {
  $('.upload').hide();
  $('.soc_tabs').show();
}

app/views/index/partial/_header.html.haml
%header.full-width
  .header-logo
    =link_to root_path do
      = image_tag 'logo.png', class: 'header-logo--image'
  .header-search.grid
    .header-search-icon.r_hide
    = form_tag index_home_path, :method => 'get', :id => "search" do
      %span.search-input-description
        %span.r_hide Searching for
      = text_field_tag :query, params[:query], placeholder: "Search query", class: 'header-search--input'
      .hide= submit_tag "Search", :name => nil, id: 'search'
      .clearfix
  %nav.header-nav
    %ul
      %li=link_to 'About', static_about_path, class: 'header-nav--link'
      %li=link_to 'Contact', static_contact_path, class: 'header-nav--link'
      %li=link_to 'Privacy Policy', static_privacy_path, class: 'header-nav--link'
  .clearfix

app/views/index/partial/_items.html.haml
.amazon-items.l-grid

  .title-big
    = params[:query].to_s.capitalize
  .title-small
    Similar Items
  .clearfix

  - if @items_iterator
    - @items_iterator.each do |key, val|
      .hide= @items_val = val
    .hide= i = 0
    -@items_val.each do |k|
      .hide=i=  i + 1
      %div{ :class=> 'amazon_item', id:'item__id_'+i.to_s}
        .item_header
          = link_to k['ItemAttributes']['Title'],k['DetailPageURL'], class: 'item_header__link'
          -#
            - if i == 1 || i == 6
              - if k['OfferSummary'] && k['OfferSummary']['LowestNewPrice']
                %p.item_header__price
                  %sup $
                  = k['OfferSummary']['LowestNewPrice']['FormattedPrice'].to_s.gsub!('$','')
              - else
                %p.item_header__price
          .clearfix
        .item_body
          .image__container
            - if k['LargeImage']
              = image_tag k['LargeImage']['URL'], class: 'item_body__image'
            - else
              %p='No photo for this image'
          .show_for_side
            .side_price
              - if k['OfferSummary'] && k['OfferSummary']['LowestNewPrice']
                %sup $
                = k['OfferSummary']['LowestNewPrice']['FormattedPrice'].to_s.gsub!('$','')
            = link_to 'Details', '#',  class: 'js_details_button', id: 'js_details_button_'+i.to_s

          .tabs
            .tabs__links
              = link_to  '#',class: 'links_link link__description link_is_active' do
                = image_tag 'description-icon.png', class: 'tab__section_link_description link__image'
                %span.link__text Description
              = link_to  request.url+"&stw=#{k['ItemAttributes']['Title']}&asin=#{k['ASIN']}", class: 'links_link link__youtube social_button_'+i.to_s, id:'get_social', :remote => true do
                = image_tag 'youtube-icon.png', class: 'tab__section_link_youtube link__image'
                %span.link__text Youtube
              = link_to  request.url+"&stw=#{k['ItemAttributes']['Title']}&asin=#{k['ASIN']}", class: 'links_link link__social social_button_'+i.to_s, id:'get_social', :remote => true do
                = image_tag 'social-icon.png', class: 'tab__section_link_social link__image'
                %span.link__text Social
              = link_to request.url+"&asin=#{k['ASIN']}&stw=#{k['ItemAttributes']['Title']}",class: 'links_link link__reviews social_button_'+i.to_s, id:'get_social', :remote => true do
                = image_tag 'reviews-icon.png', class: 'tab__section_link_review link__image link__image_review'
                %span.link__text Reviews
              = link_to '#',class: 'links_link link__price', id:'get_price', :remote => true do
                %span.link__text Price
            .tabs__sections
              .tab_section.section__description
                %p
                  %h3= k['ItemAttributes']['Title']
                  %br

                  -if k['SalesRank']
                    Sales Rank:
                    %strong= k['SalesRank']
                %br

                .reviews
                  - if k['EditorialReviews']
                    - k['EditorialReviews']['EditorialReview'].each_with_index do |a, index|
                      .review= a[1].to_s.html_safe
              .tab_section.section__price
                - if k['OfferSummary'] && k['OfferSummary']['LowestNewPrice']
                  %h2= k['OfferSummary']['LowestNewPrice']['FormattedPrice']
              .tab_section.section__youtube
                .uploadr
                  = image_tag "uploader.png", class:"image_upload"
              .tab_section.section__social
                .upload
                  = image_tag "uploader.png", class:"image_upload"
                .soc_tabs
                  .soc_tabs_links
                    = link_to  '#',class: 'soc_tab__tw' do
                      = image_tag 'twitter-icon.png', class: 'tab__section_link_description link__image'
                      %span.link__text Twitter
                    %br
                    = link_to  '#',class: 'soc_tab__gl' do
                      = image_tag 'google-icon.png', class: 'tab__section_link_description link__image link__image_google'
                      %span.link__text Google
                  .soc_tabs_section
                    .soc_tabs_twitter
                    .soc_tabs_google

              .tab_section.section__reviews
                = image_tag "uploader.png", class:"image_upload"
          //%div{class:'socials_feed_'+i.to_s}
          :javascript
            $(document).ready(function(){
                $('.social_button_#{i.to_s}').click(function(){
                    localStorage.setItem('item_count', #{i});
                });
                $('.link_reviews_#{i.to_s}').click(function(){
                    localStorage.setItem('item_count', #{i});
                });
            });
        - if k['ASIN']
          .hide.item_asin= k['ASIN']
    .clearfix

  :coffeescript
    $(".link__social, .link__youtube, .link__reviews").click ->
      $('.upload').show()
      $('.soc_tabs').hide()

app/views/index/search.html.haml
.l-wrapper
  .animate
  .animate.animate-one
  .animate.animate-second
  .animate.animate-third
  .search
    .search-header
      .search--logo-container.r_full-width
        =image_tag 'logo-white.png', class: 'search--logo-image'
      .search--description.r_hide
        Only best deals!
      .clearfix
    .search-body
      = form_tag index_home_path, :method => 'get', :id => "search" do
        = text_field_tag :query, params[:query], placeholder: "Apple iMac, Kindle Fire, etc", class: 'search-input search-reset', required: true, autofocus: true
        = submit_tag "Search", :name => nil, id: 'search', class: 'search-submit search-reset'


        .clearfix

app/views/index/show.html.haml
%h1 Index#show
%p Find me in app/views/index/show.html.haml

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buyproofed</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= yield %>
</body>
</html>